# using build procedure from: https://github.com/PHPirates/travis-ci-latex-pdf/blob/master/4-texlive

language: generic
dist: bionic

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - cd whitepaper
 - make latex

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: ../_build/main.pdf
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _build
    on:
      branch: main
